// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3sy6QshPaD7ZCgp7jWTI7-vVya3MgdDw',
    appId: '1:819413563233:web:1c9fc0c0f5093f33b0f720',
    messagingSenderId: '819413563233',
    projectId: 'rubber-vision',
    authDomain: 'rubber-vision.firebaseapp.com',
    storageBucket: 'rubber-vision.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg3V0IzFZMz2rDtjc4E41ggG1cnjScgBY',
    appId: '1:819413563233:android:10db1975278b34d9b0f720',
    messagingSenderId: '819413563233',
    projectId: 'rubber-vision',
    storageBucket: 'rubber-vision.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD63giE_mPjQJ98vFwouLBhhRk4CGd46g8',
    appId: '1:819413563233:ios:2d0ecea4e6a6d9c8b0f720',
    messagingSenderId: '819413563233',
    projectId: 'rubber-vision',
    storageBucket: 'rubber-vision.firebasestorage.app',
    iosBundleId: 'com.example.rubberVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD63giE_mPjQJ98vFwouLBhhRk4CGd46g8',
    appId: '1:819413563233:ios:2d0ecea4e6a6d9c8b0f720',
    messagingSenderId: '819413563233',
    projectId: 'rubber-vision',
    storageBucket: 'rubber-vision.firebasestorage.app',
    iosBundleId: 'com.example.rubberVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3sy6QshPaD7ZCgp7jWTI7-vVya3MgdDw',
    appId: '1:819413563233:web:ef7fc4d7ba9bbe5bb0f720',
    messagingSenderId: '819413563233',
    projectId: 'rubber-vision',
    authDomain: 'rubber-vision.firebaseapp.com',
    storageBucket: 'rubber-vision.firebasestorage.app',
  );

}